COMMENT -> "/*" ( !('*') | '*' !('/') )* "*/" ;
COMMENT -> "//" !('\n')* '\n' ;
SKIP -> ( ' ' | '\r' | '\t' )+ ;
LINEBREAKER -> '\n' ;

INTEGER -> ['0'-'9']+ ;
FLOAT -> INTEGER '.' INTEGER ;
STRING -> '\"'  ( !( '\\' | '\"' )  | '\\' . )*  '\"' ;
CHAR -> '\'' ( !('\\' | '\'' ) | '\\' . ) '\'' ;
IDENTIFIER -> ( ['a'-'z'] | ['A'-'Z'] | '_' ) ( ['a'-'z'] | ['A'-'Z'] | ['0'-'9'] | '_' )* ;

Expression -> Oring ;
Oring -> Concatnate ('|' Concatnate)* ;
Concatnate -> Removal (Removal)* ;
Removal -> Suffix ('^' Suffix)* ; 
Suffix -> Suffix ( '+' | '*' | '?' ) | Prefix ; 
Prefix -> '!' Prefix | Primary;
Primary -> CHAR | STRING | '(' Expression ')' | '[' CHAR '-' CHAR ']' ;