#pragma once

#include <cstdint>
#include <unordered_map>
#include <string>
#include <string_view>
#include <iostream>

// Auto-generated by Sathvik's Engine
enum class TokenType : uint8_t {

	// Raw Token Identifiers
	LITEREAL_CHAR,
	LITEREAL_STRING,
	LITEREAL_INTEGER,
	LITEREAL_FLOAT,
	LITEREAL_NUMBER,
	LITEREAL_IDENTIFIER,

	// Keywords
	KW_while,
	KW_bool,
	KW_if,
	KW_else,
	KW_break,
	KW_true,
	KW_float,
	KW_char,
	KW_int,
	KW_void,
	KW_nullptr,
	KW_false,
	KW_return,
	KW_continue,

	// Symbols
	SYMBOL_LINEBREAKER,
	SYMBOL_RBRACE,
	SYMBOL_LBRACE,
	SYMBOL_SLASH,
	SYMBOL_LESSER_EQUAL,
	SYMBOL_LPAREN,
	SYMBOL_EXCLAMATION,
	SYMBOL_RPAREN,
	SYMBOL_GREATER,
	SYMBOL_STAR,
	SYMBOL_COMMA,
	SYMBOL_LESSER,
	SYMBOL_EQ,
	SYMBOL_PLUS,
	SYMBOL_GREATER_EQUAL,
	SYMBOL_EXCLAMATION_EQUAL,
	SYMBOL_DASH,
	SYMBOL_ASSIGN,

};


static const std::unordered_map<std::string_view, TokenType> token_keywords = {
	{"while", TokenType::KW_while},
	{"bool", TokenType::KW_bool},
	{"if", TokenType::KW_if},
	{"else", TokenType::KW_else},
	{"break", TokenType::KW_break},
	{"true", TokenType::KW_true},
	{"float", TokenType::KW_float},
	{"char", TokenType::KW_char},
	{"int", TokenType::KW_int},
	{"void", TokenType::KW_void},
	{"nullptr", TokenType::KW_nullptr},
	{"false", TokenType::KW_false},
	{"return", TokenType::KW_return},
	{"continue", TokenType::KW_continue},

};


inline std::string_view tokenTypeToString(TokenType type) {
	switch (type) {
		case TokenType::LITEREAL_CHAR: return "CHAR";
		case TokenType::LITEREAL_STRING: return "STRING";
		case TokenType::LITEREAL_INTEGER: return "INTEGER";
		case TokenType::LITEREAL_FLOAT: return "FLOAT";
		case TokenType::LITEREAL_NUMBER: return "NUMBER";
		case TokenType::LITEREAL_IDENTIFIER: return "IDENTIFIER";

		case TokenType::KW_while: return "while";
		case TokenType::KW_bool: return "bool";
		case TokenType::KW_if: return "if";
		case TokenType::KW_else: return "else";
		case TokenType::KW_break: return "break";
		case TokenType::KW_true: return "true";
		case TokenType::KW_float: return "float";
		case TokenType::KW_char: return "char";
		case TokenType::KW_int: return "int";
		case TokenType::KW_void: return "void";
		case TokenType::KW_nullptr: return "nullptr";
		case TokenType::KW_false: return "false";
		case TokenType::KW_return: return "return";
		case TokenType::KW_continue: return "continue";

		case TokenType::SYMBOL_LINEBREAKER: return "\\n";
		case TokenType::SYMBOL_RBRACE: return "}";
		case TokenType::SYMBOL_LBRACE: return "{";
		case TokenType::SYMBOL_SLASH: return "/";
		case TokenType::SYMBOL_LESSER_EQUAL: return "<=";
		case TokenType::SYMBOL_LPAREN: return "(";
		case TokenType::SYMBOL_EXCLAMATION: return "!";
		case TokenType::SYMBOL_RPAREN: return ")";
		case TokenType::SYMBOL_GREATER: return ">";
		case TokenType::SYMBOL_STAR: return "*";
		case TokenType::SYMBOL_COMMA: return ",";
		case TokenType::SYMBOL_LESSER: return "<";
		case TokenType::SYMBOL_EQ: return "==";
		case TokenType::SYMBOL_PLUS: return "+";
		case TokenType::SYMBOL_GREATER_EQUAL: return ">=";
		case TokenType::SYMBOL_EXCLAMATION_EQUAL: return "!=";
		case TokenType::SYMBOL_DASH: return "-";
		case TokenType::SYMBOL_ASSIGN: return "=";

		default: return "UNKNOWN";
	}
}




struct ErrorInfo{
    int line;
    int col;
    std::string_view file_name;
};

struct Token {
    TokenType type;
    std::string_view lexeme;

    ErrorInfo error_info;


    Token(TokenType type, std::string_view lexeme, int line, int col, std::string_view file_name)
        : type(type), lexeme(lexeme), error_info({line, col, file_name}) {}
};


inline std::ostream& operator<<(std::ostream& os, const Token& token) {
	os << "[" << tokenTypeToString(token.type) 
	   << " | \"" << token.lexeme << "\" | " 
	   << token.error_info.file_name << "@" << token.error_info.line << ":" << token.error_info.col << "]";
	return os;
}
