#include "token_code_gen.hpp"

#include <iostream>













void TokenGenerator::output(const char* target){
    std::ofstream out(target);
    outputPreprocessorDirectives(out);
    outputTokenType(out);
    out<<"\n\n";
    outputKeywordMap(out);
    out<<"\n\n";
    outputToStringFunction(out);
    out<<"\n\n";

out<<R"(
struct ErrorInfo{
    int line;
    int col;
    std::string_view file_name;
};

struct Token {
    TokenType type;
    std::string_view lexeme;

    ErrorInfo error_info;


    Token(TokenType type, std::string_view lexeme, int line, int col, std::string_view file_name)
        : type(type), lexeme(lexeme), error_info({line, col, file_name}) {}
};


inline std::ostream& operator<<(std::ostream& os, const Token& token) {
	os << "[" << tokenTypeToString(token.type) 
	   << " | \"" << token.lexeme << "\" | " 
	   << token.error_info.file_name << "@" << token.error_info.line << ":" << token.error_info.col << "]";
	return os;
}
)";

}

std::ofstream& TokenGenerator::outputPreprocessorDirectives(std::ofstream& out){
    if (!out.is_open()) {
        std::cerr<<"Filenot Open\n";
        return out;
    }

    auto printlib = [&out](const std::string& lib) {
        out << "#include <" << lib << ">\n";
    };

    out << "#pragma once\n\n";
    printlib("cstdint");
    printlib("unordered_map");
    printlib("string");
    printlib("string_view");
    printlib("iostream");
    out << "\n// Auto-generated by Sathvik's Engine\n";

    return out;
}


std::ofstream& TokenGenerator::outputTokenType(std::ofstream& out) {
    out << "enum class TokenType : uint8_t {\n";


    auto printer = [&out](std::unordered_map<std::string, std::string>& tokens, const std::string& section_name) {
        
        out << "\n\t" << section_name << "\n";
        for (const auto& [lexeme, enum_name] : tokens) {
            out << "\t" << enum_name << ",\n";
        }
    };

    printer(identifier_tokens, "// Raw Token Identifiers");
    printer(keywords_tokens, "// Keywords");
    printer(symbol_tokens, "// Symbols");
    //Trailing Zeros
    out << "\n};\n";

    return out;
}

std::ofstream& TokenGenerator::outputKeywordMap(std::ofstream& out){
    out<<"static const std::unordered_map<std::string_view, TokenType> token_keywords = {\n";
    for (const auto& [lexeme, enum_name] : keywords_tokens) {
        out << "\t{\"" << lexeme << "\", TokenType::" << enum_name << "},\n";
    }
    //Trailing Zeros
    out << "\n};\n";
    return out;
}





std::ofstream& TokenGenerator::outputToStringFunction(std::ofstream& out) {
	out << "inline std::string_view tokenTypeToString(TokenType type) {\n";
	out << "\tswitch (type) {\n";

    auto printer = [&out](std::unordered_map<std::string, std::string>& tokens) {
        auto escape_string = [](std::string_view s){
            std::string result;
            for (char c : s) {
                switch (c) {
                    case '\n': result += "\\\\n"; break;
                    case '\t': result += "\\\\t"; break;
                    case '\r': result += "\\\\r"; break;
                    case '\"': result += "\\\\\""; break;
                    case '\\': result += "\\\\\\"; break;
                    default:   result += c;     break;
                }
            }
            return result;
        };
        for (const auto& [lexeme, enum_name] : tokens) {
            out << "\t\tcase TokenType::" << enum_name << ": return \"" << escape_string(lexeme) << "\";\n";
        }out<<'\n';
    };
    printer(identifier_tokens);
    printer(keywords_tokens);
    printer(symbol_tokens);

	out << "\t\tdefault: return \"UNKNOWN\";\n";
	out << "\t}\n";
	out << "}\n\n";
	return out;
}